


export enum ActionType {
    OPEN_SIDEBAR = 'OPEN_SIDEBAR',
    CLOSE_SIDEBAR = 'CLOSE_SIDEBAR',
    GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN',
    GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR',
    GET_SINGLE_PRODUCT_BEGIN = 'GET_SINGLE_PRODUCT_BEGIN',
    GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS',
    GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR',
    GET_FEATURED_PRODUCTS_BEGIN = 'GET_FEATURED_PRODUCTS_BEGIN',
    GET_FEATURED_PRODUCTS_SUCCESS = 'GET_FEATURED_PRODUCTS_SUCCESS',
    GET_FEATURED_PRODUCTS_ERROR = 'GET_FEATURED_PRODUCTS_ERROR',
    SIDEBAR_OPEN = 'SIDEBAR_OPEN',
    SIDEBAR_CLOSE = 'SIDEBAR_CLOSE',
}


