


export enum ActionType {
    OPEN_SIDEBAR = 'OPEN_SIDEBAR',
    CLOSE_SIDEBAR = 'CLOSE_SIDEBAR',
    GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN',
    GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR',
    GET_SINGLE_PRODUCT_BEGIN = 'GET_SINGLE_PRODUCT_BEGIN',
    GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS',
    GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR',
    LOAD_PRODUCTS = 'LOAD_PRODUCTS',
    SET_GRIDVIEW = 'SET_GRIDVIEW',
    SET_LISTVIEW = 'SET_LISTVIEW',
    UPDATE_SORT = 'UPDATE_SORT',
    SORT_PRODUCTS = 'SORT_PRODUCTS',
    UPDATE_FILTERS = 'UPDATE_FILTERS',
    FILTER_PRODUCTS = 'FILTER_PRODUCTS',
    CLEAR_FILTER =  "CLEAR_FILTER",
}


